apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeptodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zeptodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector:
    {{- include "zeptodb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
---
{{- if .Values.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeptodb.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zeptodb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "zeptodb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
